# Generated by Django 2.1.1 on 2018-09-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssido_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='unknown', max_length=100)),
                ('description', models.CharField(blank=True, help_text='simple description text', max_length=100)),
                ('content', models.TextField(default='unknown', max_length=500)),
            ],
        ),
    ]
